name = "blog-likes"
account_id = "22812d251a775438597b379aebc4b330"
compatibility_date = "2025-04-01"
main = "src/index.js"
workers_dev = false

[[d1_databases]]
binding = "DB"
database_name = "blog-likes"
database_id = "eda2c151-8f04-4df0-a52e-f7efc5268753"

[observability.logs]
enabled = true


